# SPDX-License-Identifier: Apache-2.0
def sum_as_string(a: int, b: int) -> str: ...
def prn_canonicalize(s: str) -> str: ...
def prn_error_kind(s: str) -> str: ...
def prn_build(service: str, region: str, org: str, resource_type: str, resource_id: str) -> str: ...
def prn_service(s: str) -> str: ...
def prn_region(s: str) -> str: ...
def prn_org(s: str) -> str: ...
def prn_resource_type(s: str) -> str: ...
def prn_resource_id(s: str) -> str: ...
def mint_uuid7(unix_ms: float, rand_hex: str) -> str: ...
def prn_cedar_entity_type(s: str) -> str: ...
def prn_cedar_entity_id(s: str) -> str: ...
