// SPDX-License-Identifier: Apache-2.0

//! Generated protobuf + gRPC bindings for Paigasus (prost + tonic).
//!
//! The source of truth is `contracts/proto`; code is generated by `buf generate`
//! into `src/generated/` and committed (ADR-0004). Empty until the first protos
//! land; the `generated` module is wired up then (alongside SMA-389).
