// SPDX-License-Identifier: Apache-2.0

//! Generated protobuf + gRPC bindings for Paigasus (prost + tonic).
//!
//! Source of truth: `contracts/proto`; generated by `buf generate` into
//! `src/generated/` and committed (ADR-0004). Regenerate via
//! `moon run contracts:generate`.

pub mod paigasus {
    pub mod gateway {
        pub mod v1 {
            // Generated code is excluded from the strict lint gate.
            #![allow(clippy::all, warnings)]
            include!("generated/paigasus/gateway/v1/paigasus.gateway.v1.rs");
            include!("generated/paigasus/gateway/v1/paigasus.gateway.v1.tonic.rs");
        }
    }
    pub mod common {
        pub mod v1 {
            // Generated code is excluded from the strict lint gate.
            #![allow(clippy::all, warnings)]
            // Only the prost file: audit.proto declares no service, so
            // neoeinstein-tonic emits no `.tonic.rs` for this package.
            include!("generated/paigasus/common/v1/paigasus.common.v1.rs");
        }
    }
    pub mod iam {
        pub mod v1 {
            // Generated code is excluded from the strict lint gate.
            #![allow(clippy::all, warnings)]
            // Only the prost file: iam.proto (M0) declares no service, so
            // neoeinstein-tonic emits no `.tonic.rs` for this package.
            include!("generated/paigasus/iam/v1/paigasus.iam.v1.rs");
        }
    }
}

/// Thin `Auditable` contract layered on the generated `common::v1::AuditMetadata`.
pub mod audit;
