// SPDX-License-Identifier: Apache-2.0

export type { Auditable } from './audit.js';
export { ActorSchema } from './generated/paigasus/common/v1/actor_pb.js';
export type { Actor } from './generated/paigasus/common/v1/actor_pb.js';
export { AuditMetadataSchema } from './generated/paigasus/common/v1/audit_pb.js';
export type { AuditMetadata } from './generated/paigasus/common/v1/audit_pb.js';
export { capabilityWireKey } from './capability.js';
export { Capability, ServiceInfoSchema, ServiceInfoService } from './generated/paigasus/common/v1/service_info_pb.js';
export type { ServiceInfo } from './generated/paigasus/common/v1/service_info_pb.js';

// The canonical error registry (ADR-0019) and its codec. ErrorReason and
// ErrorDomain are REGISTRIES, never wire types — no proto field has either
// type, and the wire carries the kebab strings the codec produces.
export { ErrorDomain, ErrorDomainSchema, ErrorReason, ErrorReasonSchema } from './generated/paigasus/common/v1/error_pb.js';
export { asWireDomain, asWireReason, fromWireDomain, fromWireReason } from './error.js';

// google.rpc.ErrorInfo, generated by the second buf template (SMA-624). This is
// what ConnectError.findDetails(desc) needs; there is no schema-free overload.
export { ErrorInfoSchema } from './generated/google/rpc/error_details_pb.js';
export type { ErrorInfo } from './generated/google/rpc/error_details_pb.js';
