/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Node-callable wrapper over [`paigasus_kernel::sum`] (the canonical first-binding shape — a
 * real value crossing the FFI boundary). Uses `i32` so napi-rs maps the surface to a JS
 * `number` deterministically (spec decision #5 / review F3): an `i64` return can surface as a
 * `BigInt` on some napi-rs versions (`5n !== 5`). The kernel fn is `i64`; we cast at the
 * boundary. A future kernel fn needing the full `i64` range gets explicit BigInt handling then.
 */
export declare function sum(a: number, b: number): number
