/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Mint a UUIDv7 from an injected millisecond timestamp and a 20-char lowercase hex string of
 * entropy (throws `"bad-rand-hex"` if `rand_hex` is malformed).
 */
export declare function mintUuid7(unixMs: number, randHex: string): string

/** Build a PRN from typed fields and return its canonical form, or throw `kind()`. */
export declare function prnBuild(service: string, region: string, org: string, resourceType: string, resourceId: string): string

/** Parse `s` and return its canonical form, or throw `kind()` on an invalid PRN. */
export declare function prnCanonicalize(s: string): string

/** Parse `s` and return its Cedar entity id, or throw `kind()`. */
export declare function prnCedarEntityId(s: string): string

/** Parse `s` and return its Cedar entity type (e.g. `Pgs::Iam::Project`), or throw `kind()`. */
export declare function prnCedarEntityType(s: string): string

/** Return the stable `PrnError::kind()` token for an invalid PRN, or `""` if `s` parses. */
export declare function prnErrorKind(s: string): string

/** Parse `s` and return its org field (hyphenated UUID, or `""` if absent), or throw `kind()`. */
export declare function prnOrg(s: string): string

/** Parse `s` and return its region field, or throw `kind()`. */
export declare function prnRegion(s: string): string

/** Parse `s` and return its resource-id field (hyphenated UUID), or throw `kind()`. */
export declare function prnResourceId(s: string): string

/** Parse `s` and return its resource-type field, or throw `kind()`. */
export declare function prnResourceType(s: string): string

/** Parse `s` and return its service field, or throw `kind()`. */
export declare function prnService(s: string): string

/**
 * Node-callable wrapper over [`paigasus_kernel::sum`] (the canonical first-binding shape — a
 * real value crossing the FFI boundary). Uses `i32` so napi-rs maps the surface to a JS
 * `number` deterministically (spec decision #5 / review F3): an `i64` return can surface as a
 * `BigInt` on some napi-rs versions (`5n !== 5`). The kernel fn is `i64`; we cast at the
 * boundary. A future kernel fn needing the full `i64` range gets explicit BigInt handling then.
 */
export declare function sum(a: number, b: number): number
